/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package explorador_ficheros;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author The Test
 */
public class Explorador extends javax.swing.JFrame {

    private JFileChooser selectorArchivos;

    public Explorador() {
        initComponents();
        String home = System.getProperty("user.dir");

        selectorArchivos = new JFileChooser();
        selectorArchivos.setDialogTitle("SELECCIÓN DE ARCHIVOS");
        selectorArchivos.addChoosableFileFilter(new FileNameExtensionFilter("Archivos Java(*.java,*.class)", "java", "class"));
        selectorArchivos.addChoosableFileFilter(new FileNameExtensionFilter("Adobe (PDF)", "pdf"));
        selectorArchivos.addChoosableFileFilter(new FileNameExtensionFilter("Microsoft Word", "docx"));
        selectorArchivos.addChoosableFileFilter(new FileNameExtensionFilter("Imagenes", "jpeg", "jpg", "png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar Varios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Copiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        File aBorrar;
        int seleccion = selectorArchivos.showOpenDialog(selectorArchivos);
        System.out.println(seleccion);

        if (seleccion == 0) {
            aBorrar = selectorArchivos.getSelectedFile();

            if (JOptionPane.showConfirmDialog(selectorArchivos, "Estás seguro de que quieres eliminar " + aBorrar.getName()) == 0) {
                aBorrar.delete();
                JOptionPane.showMessageDialog(selectorArchivos, "El archivo " + aBorrar.getName() + " ha sido eliminado");
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        File[] aBorrar;
        selectorArchivos.setMultiSelectionEnabled(true);
        int seleccion = selectorArchivos.showOpenDialog(selectorArchivos);

        if (seleccion == 0) {

            aBorrar = new File[selectorArchivos.getSelectedFiles().length];
            aBorrar = selectorArchivos.getSelectedFiles();

            String archivos = "";
            for (File f : aBorrar) {
                archivos = archivos + f.getName() + " ";
            }
            if (JOptionPane.showConfirmDialog(selectorArchivos, "Estás seguro de que quieres eliminar " + archivos) == 0) {
                for (File ff : aBorrar) {
                    ff.delete();
                }
                JOptionPane.showMessageDialog(selectorArchivos, "Los archivos " + archivos + " han sido eliminados");
            }

        }

        selectorArchivos.setMultiSelectionEnabled(false);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int seleccionPegar = selectorArchivos.showOpenDialog(selectorArchivos);

        if (JOptionPane.showConfirmDialog(selectorArchivos, "Estás seguro de que quieres crear ?") == 0) {
            File aCrear = new File(selectorArchivos.getCurrentDirectory().getPath() + "\\hellothere.txt");
            try {
                aCrear.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Explorador.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        File aCopiar;
        int seleccion = selectorArchivos.showOpenDialog(selectorArchivos);
        System.out.println(seleccion);

        if (seleccion == 0) {
            aCopiar = selectorArchivos.getSelectedFile();

            if (JOptionPane.showConfirmDialog(selectorArchivos, "Estás seguro de que quieres copiar " + aCopiar.getName()) == 0) {

                JOptionPane.showMessageDialog(selectorArchivos, "El archivo " + aCopiar.getName() + " ha sido copiado");
            }

            int seleccionPegar = selectorArchivos.showOpenDialog(selectorArchivos);
            if (seleccionPegar == 0) {

                if (JOptionPane.showConfirmDialog(selectorArchivos, "Estás seguro de que quieres pegar " + aCopiar.getName() + " ?") == 0) {
                    String directorio = selectorArchivos.getCurrentDirectory().getAbsolutePath();

                    try {
                        Files.copy(aCopiar.toPath(), selectorArchivos.getSelectedFile().toPath());
                    } catch (IOException ex) {
                        Logger.getLogger(Explorador.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    JOptionPane.showMessageDialog(selectorArchivos, "El archivo " + aCopiar.getName() + " ha sido pegado");
                }

            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Explorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Explorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Explorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Explorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Explorador().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
